#ifndef BOARD_H
#define BOARD_H

#define LED_GREEN_PORT GPIOA
#define LED_GREEN_PIN 12
#define LED_RED_PORT GPIOA
#define LED_RED_PIN 11

#define CC2500_GPIO_PORT GPIOA
#define CC2500_CSN_PIN 4
#define CC2500_SCK_PIN 5
#define CC2500_MISO_PIN 6
#define CC2500_MOSI_PIN 7
#define CC2500_GDO2_PIN 3

#define RF_LNA_PORT GPIOB
#define RF_LNA_PIN 4
#define RF_LNA_ON_LEVEL 1

#define RF_PA_PORT GPIOA
#define RF_PA_PIN 15
#define RF_PA_ON_LEVEL 1

#define RF_ANTENNA_SWITCH_PORT GPIOC
#define RF_ANTENNA_SWITCH_PIN 14
#define RF_ANTENNA_A_LEVEL 1

#define RF_ANTENNA_SWITCH_PORT2 GPIOC
#define RF_ANTENNA_SWITCH_PIN2 15
#define RF_ANTENNA_A_LEVEL2 1

#endif