#pragma once

#include "board.h"

#define BOOTLOADER_LED_GREEN_PORT LED_GREEN_PORT
#define BOOTLOADER_LED_GREEN_PIN LED_GREEN_PIN
#define BOOTLOADER_LED_RED_PORT LED_RED_PORT
#define BOOTLOADER_LED_RED_PIN LED_RED_PIN